# HTTP 代理
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890

# HTTPS 代理（大部分构建下载走这个）
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890

# 非代理主机列表（内网或本地不走代理，用竖线 | 分隔）
systemProp.http.nonProxyHosts=localhost|127.0.0.1|*.local|*.internal
systemProp.https.nonProxyHosts=localhost|127.0.0.1|*.local|*.internal

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=1.0.0
maven_group=org
archives_base_name=linear
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.155.2+26.2
